// VANTAGE MCP tool — open_fix_pr
//
// Takes a verified patch, applies it to a branch, commits it, pushes,
// and opens a PR via the `gh` CLI. Deliberately uses `gh` instead of the
// Octokit SDK to avoid a new runtime dependency and to piggy-back on
// whatever auth the user has already configured for `gh`. If `gh` isn't
// available, we fall back to a branch-and-commit-only mode and return
// instructions for the caller to open the PR manually.

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as crypto from 'crypto';
import { OpenFixPrInputType } from '../schemas';

export interface OpenFixPrResult {
  success: boolean;
  branch: string;
  commitSha?: string;
  prUrl?: string;
  /** If PR creation wasn't possible, the command the caller should run. */
  manualNextStep?: string;
  error?: string;
}

export async function toolOpenFixPr(input: OpenFixPrInputType): Promise<OpenFixPrResult> {
  const repoPath = path.resolve(input.target_path);

  if (!fs.existsSync(path.join(repoPath, '.git'))) {
    return {
      success: false,
      branch: '',
      error: `${repoPath} is not a git repository`,
    };
  }

  const branch = input.branch ?? autoBranchName();
  const base = input.base ?? detectDefaultBranch(repoPath);

  // Apply the patch on a throwaway branch to isolate the change. We don't
  // touch the user's current branch unless the PR tool is explicitly given
  // the same branch name they're on — opinionated but saves a lot of
  // accidental "why is my working tree modified" bug reports.
  try {
    execSync(`git -C ${sh(repoPath)} fetch origin ${sh(base)}`, { stdio: 'pipe' });
  } catch {
    // No origin or network — continue with local base ref.
  }

  try {
    execSync(`git -C ${sh(repoPath)} checkout -B ${sh(branch)} ${sh(base)}`, { stdio: 'pipe' });
  } catch (err: unknown) {
    return {
      success: false,
      branch,
      error: `Failed to create branch ${branch} from ${base}: ${(err as Error).message}`,
    };
  }

  // Apply the patch
  const patchFile = path.join(os.tmpdir(), `vantage-pr-${crypto.randomUUID()}.patch`);
  fs.writeFileSync(patchFile, input.patch, 'utf8');
  try {
    execSync(`git -C ${sh(repoPath)} apply --index ${sh(patchFile)}`, { stdio: 'pipe' });
  } catch (err: unknown) {
    try { fs.unlinkSync(patchFile); } catch { /* ignore */ }
    return {
      success: false,
      branch,
      error: `git apply failed: ${(err as Error).message}`,
    };
  }
  try { fs.unlinkSync(patchFile); } catch { /* ignore */ }

  // Commit
  const commitMsg = `${input.title}\n\nVANTAGE auto-fix. This commit was generated and verified by VANTAGE's\n\`generate_fix\` → \`verify_fix\` pipeline. The patch passed the four-gate\ncheck (applies cleanly; original finding resolved; no new HIGH/CRITICAL\nfindings; AURORA score non-decreasing within 0.02).\n`;
  let commitSha: string;
  try {
    execSync(
      `git -C ${sh(repoPath)} -c user.email=vantage@jourdanlabs.ai -c user.name="VANTAGE auto-fix" commit -m ${sh(commitMsg)}`,
      { stdio: 'pipe' }
    );
    commitSha = execSync(`git -C ${sh(repoPath)} rev-parse HEAD`, { encoding: 'utf8' }).trim();
  } catch (err: unknown) {
    return {
      success: false,
      branch,
      error: `git commit failed: ${(err as Error).message}`,
    };
  }

  // Push
  try {
    execSync(`git -C ${sh(repoPath)} push -u origin ${sh(branch)}`, { stdio: 'pipe' });
  } catch (err: unknown) {
    return {
      success: false,
      branch,
      commitSha,
      error: `git push failed: ${(err as Error).message}`,
      manualNextStep: `git -C ${repoPath} push -u origin ${branch}  # then open a PR manually`,
    };
  }

  // Try `gh` CLI for the PR
  const hasGh = (() => {
    try {
      execSync('command -v gh', { stdio: 'pipe' });
      return true;
    } catch {
      return false;
    }
  })();

  if (!hasGh) {
    return {
      success: true,
      branch,
      commitSha,
      manualNextStep: `gh not found. Run: gh pr create --title ${sh(input.title)} --base ${base} --head ${branch}${input.body ? ` --body ${sh(input.body)}` : ''}`,
    };
  }

  const bodyArg = input.body
    ? ` --body ${sh(input.body)}`
    : ' --body "Auto-generated by VANTAGE. See commit message for verification details."';
  try {
    const out = execSync(
      `gh pr create --title ${sh(input.title)} --base ${sh(base)} --head ${sh(branch)}${bodyArg}`,
      { encoding: 'utf8', cwd: repoPath }
    ).trim();
    const urlMatch = out.match(/https?:\/\/\S+/);
    return {
      success: true,
      branch,
      commitSha,
      prUrl: urlMatch ? urlMatch[0] : out,
    };
  } catch (err: unknown) {
    return {
      success: false,
      branch,
      commitSha,
      error: `gh pr create failed: ${(err as Error).message}`,
      manualNextStep: `gh pr create --title ${sh(input.title)} --base ${base} --head ${branch}`,
    };
  }
}

function autoBranchName(): string {
  const slug = Math.random().toString(36).slice(2, 8);
  return `vantage/autofix-${slug}`;
}

function detectDefaultBranch(repoPath: string): string {
  // Prefer whatever origin/HEAD points to
  try {
    const ref = execSync(
      `git -C ${sh(repoPath)} symbolic-ref refs/remotes/origin/HEAD`,
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }
    ).trim();
    return ref.split('/').pop() ?? 'main';
  } catch {
    // Fallback: whichever of main/master exists locally
    try {
      execSync(`git -C ${sh(repoPath)} show-ref --verify --quiet refs/heads/main`, { stdio: 'pipe' });
      return 'main';
    } catch {
      return 'master';
    }
  }
}

/** shell-quote a string, handling newlines. */
function sh(s: string): string {
  return `'` + s.replace(/'/g, `'\\''`) + `'`;
}
